language: r
cache: packages
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel
  - bioc-devel
  
notifications:
  email:
    on_success: change
    on_failure: change
    
    
## dependencies that need to be installed beforehand if any
sudo: true
before_install:
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags
  - sudo apt-get update
  - R -e 'source("https://install-github.me/r-lib/remotes")'



# environment variables set for all builds
env:
  global:
    - BIOC_USE_DEVEL="FALSE"  ## Use the current release version












