language: r
cache: packages
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

notifications:
  email:
    on_success: change
    on_failure: change
    
    
## dependencies that need to be installed beforehand if any
sudo: true
before_install:
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags

# environment variables set for all builds
env:
  global:
    - BIOC_USE_DEVEL="FALSE"  ## Use the current release version

# we need to install BiocInstaller for testing Bioconductor packages
bioc_required: true












